#!/usr/bin/env bash

sudo apt update && sudo apt upgrade
sudo apt install tmux \
                 vim \
                 htop \
                 virtualenv \
                 wget \
                 curl \
                 git \
                 git-lfs

. setup_vscode
. setup_docker
. setup_chrome
. setup_clion
. setup_nvidia