#!/usr/bin/env bash

sudo apt update && sudo apt upgrade
sudo apt install -y wget

wget https://github.com/junegunn/fzf/releases/download/v0.58.0/fzf-0.58.0-linux_amd64.tar.gz
tar -xvzf fzf-0.58.0-linux_amd64.tar.gz && rm fzf-0.58.0-linux_amd64.tar.gz
sudo mv fzf /usr/local/bin

echo "# Set up fzf key bindings and fuzzy completion" >> ~/.bashrc
echo 'eval "$(fzf --bash)"' >> ~/.bashrc