#!/usr/bin/env bash

sudo apt update && sudo apt upgrade
sudo apt install -y tmux \
                    vim \
                    htop \
                    virtualenv \
                    wget \
                    curl \
                    git \
                    git-lfs \
                    libx11-dev \
                    xorg-dev \
                    libglu1-mesa-dev \
                    xournal

. setup_vscode
. setup_docker
. setup_chrome
. setup_brave
. setup_clion
. setup_nvidia
- setup_fzf