#!/usr/bin/env bash

curl --fail --silent --show-error --location https://dl.google.com/linux/linux_signing_key.pub \
    | gpg --dearmor \
    | sudo tee /etc/apt/keyrings/google.gpg

echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google.gpg] https://dl.google.com/linux/chrome/deb/ stable main" \
    | sudo tee /etc/apt/sources.list.d/google-chrome.list

# We want to manage the Google Chrome repository manually, so that we can use
# the modern `signed-by` method of trusting their key only for their repo, not
# globally.
sudo tee /etc/default/google-chrome <<EOF
repo_add_once=false
repo_reenable_on_distupgrade=false
EOF

# They'll auto-install their key globally daily, but we don't want it there.
sudo ln --symbolic /dev/null /etc/apt/trusted.gpg.d/google-chrome.gpg

sudo apt update
sudo apt install google-chrome-stable